limits_type0 = [
    [3, 3, 1, 2],
    [2, 1, 3, 3]
]
limits_type1 = [
    [0, 1, 3, 1],
    [1, 3, 1, 0]
]
board = [
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
]

[[blocks]]
index = 1
type = 0
shape = [
    [1, 1],
    [1, 0],
    [1, 1]
]

[[blocks]]
index = 2
type = 0
shape = [
    [0, 0, 1],
    [1, 1, 1]
]

[[blocks]]
index = 3
type = 1
shape = [
    [0,1,0],
    [1,1,1],
    [0,1,0]
]

