limits_type0 = [
    [3, 4, 5, 4, 3],
    [1, 3, 5, 5, 5]
]
limits_type1 = [
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
]
board = [
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]
]

[[blocks]]
index = 1
type = 0
shape = [
    [0, 1, 0],
    [1, 1, 1]
]

[[blocks]]
index = 2
type = 0
shape = [
    [0, 0, 1],
    [1, 1, 1]
]

[[blocks]]
index = 3
type = 0
shape = [
    [1, 1, 0],
    [0, 1, 1]
]

[[blocks]]
index = 4
type = 0
shape = [
    [1, 1, 0],
    [0, 1, 1]
]

[[blocks]]
index = 5
type = 0
shape = [
    [1, 1],
    [1, 0]
]