nrows = 5
ncols = 5

[[limits]]
type = 0
cols = [3, 4, 5, 4, 3]
rows = [1, 3, 5, 5, 5]

[[limits]]
type = 1
cols = [0, 0, 0, 0, 0]
rows = [0, 0, 0, 0, 0]

[[fixed]]
type = 0
coords = []

[[fixed]]
type = 1
coords = []

invalid = [
    [0, 0],
    [0, 4]
]


[[blocks]]
index = 1
type = 0
shape = [
    [0, 1, 0],
    [1, 1, 1]
]

[[blocks]]
index = 2
type = 0
shape = [
    [0, 0, 1],
    [1, 1, 1]
]

[[blocks]]
index = 3
type = 0
shape = [
    [1, 1, 0],
    [0, 1, 1]
]

[[blocks]]
index = 4
type = 0
shape = [
    [1, 1, 0],
    [0, 1, 1]
]

[[blocks]]
index = 5
type = 0
shape = [
    [1, 1],
    [1, 0]
]